### ISSUE TITLE
`Octo comment add` command broken

### ISSUE THREAD

**Issue by harjotgill** [pwntester/octo.nvim#286] opened 2022-04-22 00:31 UTC
## Issue Description

Type: *bug report*
Unable to add review comments via the command `Octo comment add`. 
The `<space>ca` binding and `OctoAddReviewComment` command still works.

### Tell us your environment

macOS - VimrR

**Comment by pwntester** [comment] 2022-04-22 15:53
testing regular issue comment from Octo with `Octo comment add`

**Comment by pwntester** [comment] 2022-04-22 16:20
Hi, thanks for reporting, let me know if the issue is now fixed for youj

**Closed** 2022-04-22 16:20 UTC
