### ISSUE TITLE
Bug: Throws error every time submitting review but still submits review

### ISSUE THREAD

**Issue by joshpetit** [pwntester/octo.nvim#223] opened 2021-12-17 13:14 UTC
## Issue Description

Type: Bug

### Describe what happened (or what feature you want)
Octo works perfectly fine for everything, but it throws an error everytime you submit your PR review. The review is still submitted, but this error is thrown:

```
Error executing vim.schedule lua callback: ...im/site/pack/packer/start/octo.nvim/lua/octo/reviews.lua:275: Invalid window id: 1486
stack traceback:
        [C]: in function 'nvim_win_close'
        ...im/site/pack/packer/start/octo.nvim/lua/octo/reviews.lua:275: in function 'cb'
        ...re/nvim/site/pack/packer/start/octo.nvim/lua/octo/gh.lua:82: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

### How to reproduce it (as minimally and precisely as possible)

1. Finish reviewing PR
2. run Octo review submit
3. Do one of the actions (C-m C-r or C-a)
4. See the error posted above
5. Review is submitted sucessfully

### Tell us your environment
Nvim 0.6, Arch

### Anything else we need Know?

I really like this bug report template, it doesn't ask for a million things haha

**Comment by pwntester** [comment] 2021-12-20 22:23
Thanks for reporting!, can you please check if the issue is fixed now?

**Closed** 2021-12-20 22:23 UTC

**Comment by joshpetit** [comment] 2021-12-22 14:52
Awesome! Fixed, thanks.
