### ISSUE TITLE
Octo `comment delete` closes the window

### ISSUE THREAD

**Issue by ribelo** [pwntester/octo.nvim#398] opened 2023-05-24 00:35 UTC
## Issue Description

Octo `comment delete` closes diff window

Type: *bug report*
### Describe what happened (or what feature you want)

This basically prevents further work on the review.

### Describe what you expected to happen

Removing the comment doesn't close the window and doesn't prevent continuing the review.

### How to reproduce it (as minimally and precisely as possible)

1. Create a review comment `<C-a>`
2. Delete a review comment `<C-d>`

**Comment by pleicht** [comment] 2023-08-16 17:18
I also have this issue.

For additional clarity.  When you delete a comment from the left pane, the buffer stops being a diff view and turns into just a split view of the file you were reviewing in the PR.  

Subsequent commands that are attempted to run return `Cannot find diff window` (which kinda makes sense given the above bug caused the diff view to exit following a comment being deleted)

**Comment by pwntester** [comment] 2023-08-25 08:51
Sorry for the late, late response. Let me know if the issue is fixed on your side

**Closed** 2023-08-25 08:51 UTC
