### ISSUE TITLE
Filter by pr title + pr number

### ISSUE THREAD

**Issue by tami5** [pwntester/octo.nvim#60] opened 2021-01-06 03:44 UTC
Using telescopes' picker, it would eb nice to be able to filter by pr titles in addition to pr numbers

**Comment by pwntester** [comment] 2021-01-06 13:56
thanks for the suggestion @tami5, maybe you or @Conni2461 can send a PR fixing it. Not sure how to tell telescope picker what columns should be used for filtering.

**Comment by tami5** [comment] 2021-01-06 14:18
Sure thing @pwntester

**Comment by pwntester** [comment] 2021-01-09 18:28
@tami5 can you point me to the telescope docs or example where I can see how to implement this?

**Comment by tami5** [comment] 2021-01-09 18:46
hey @pwntester hopefully tomorrow I will take a look and open a pr, but from a review of telescope buffers picker, change the sorter to `sorter = conf.generic_sorter(opts)` might solve this

**Comment by Conni2461** [comment] 2021-01-09 19:13
Oh now i see what tami meant 😆 
I just didn't get it 4 days ago.
Changing the sorter doesn't change anything really. The problem is in your entry_makers like `gen_from_issue`. We are sorting over the ordinal. So if `ordinal = number` we are fuzzy finding over the issue numbers. If `ordinal = title` we are fuzzy finding over the titles. Most of the times we are doing something like this: `ordinal = number .. ' ' .. title`. E.g. for `reqiure'telescope.builtin'.buffers

**Comment by pwntester** [comment] 2021-01-09 23:12
thanks @Conni2461 and @tami5! I think it should be fixed in #56. Will leave this open until this PR gets merged though

**Closed** 2021-01-16 18:24 UTC
