### ISSUE TITLE
Feature request - review PRs at commit level

### ISSUE THREAD

**Issue by weilbith** [pwntester/octo.nvim#98] opened 2021-02-23 15:51 UTC
Hey :wave: 
Reviewing a PR at whole can be quite cumbersome often times. For tiny ones this might work, and also it  should be the goal to have smallish PRs, this is isn't always the cause, nor does the following only apply to big PRs. So I basically always review PRs commit wise.  Thereby I can read first the commit message with the abstract, why this was necessary, the decision making etc. With that knowledge I can then start to read the code and better evaluate it, fully concentrating on this change without guessing what he did or which parts belong together to achieve what change. In the end I list all my comments for all commits together and see if something might got resolved at a later commit because the contributor does not have had a linear history or I was stupid or...
If I experience this with Octo atm, such workflow is not possible yet. Correct? If it is, could you give me a hint how to do it? If not, would you agree to discuss about how such feature could be added?

**Comment by pwntester** [comment] 2021-02-23 16:03
Nice idea! You can currently see pr commits with `Octo pr commits` but it would nice to add a `Octo review commit` which pops up a similar menu but then starts a review of that commit. This seems easy to implement given the current review implementation. 

Does that sound ok to you? Any ideas of how the workflow could be are welcome!

**Comment by tami5** [comment] 2021-02-23 16:11
:heart_eyes: I like that

**Comment by weilbith** [comment] 2021-02-23 16:11
Hmm. But in the end it should still be single review after all.
I was thinking of having the quickfix list and location list combined. One for the commits and one for the changes in the currently selected commit. But as location lists are actually bound to buffers (also some plugins bound them to windows :grimacing: ), I'm not sure if this would work.
I'm a little afraid that you could get lost in the process using the `Octo review commit` for all commits of a PR. As we discussed earlier I like the static list as it is something that I can follow while fully focusing my mind on the code changes.

**Comment by weilbith** [comment] 2021-02-23 16:15
Maybe we could have a split like this:

```
+------------+--------------+
|    A       |        B     |
|            |              |
+------------+--------------+
|    C       |        D     |
+------------+--------------+
```

Where `A` and `B` are still the diff view, `C` the list of commits of the PR and `D` a quickfix list with the locations of the current commit.

**Comment by weilbith** [comment] 2021-02-23 16:16
Not sure if this is related but as the `D` location is currently used to see the comments, this could be another use-case for pop-ups. So in the head buffer we have icons in the sign column for lines of code which have a comment and a command to open them in a floating window where they can be also edit or adding a new comment if there is none yet.

**Comment by pwntester** [comment] 2021-02-23 21:38
This should be easy to implement in the following manner:
- `Octo review commit` -> open a Telescope menu showing all commits
- Pick a commit -> A new tab opens with the left/right/qf layout
- Add comments on any changed file of the commit
- when done, do `Octo review commit` which will show the menu again
- Pick a commit -> close previous tab and show a new tab opens with the left/right/qf layout
- Repeat as needed
- When ready, `Octo review submit`

**Comment by weilbith** [comment] 2021-02-24 07:24
Okay, I must admit that doesn't sound too bad. :grimacing:
Is it possible to strictly sort the list in Telescope? And could you start Telescope with the prompt in normal mode, as you likely don't want to filter/search, but just directly move and select?
And it would be also great if you could somehow see at which commit you currently are (maybe preselect it?) So when you reviewed a (too big) commit and lost track which you selected last, you get reminded there.
And I would assume that the Telescope preview window would show me the commit message?

**Comment by pwntester** [comment] 2021-02-24 17:28
This is a good question for @tami5 and @Conni2461 which are our in-house Telescope experts. But I think you can basically do anything with a custom finder. Not sure if you can even hide the prompt buffer window.
In the other hand, I dont think you can scroll the result buffer, so if you get more commits than the height of the results windows you would lose some results.

**Comment by tami5** [comment] 2021-02-24 18:09
> Is it possible to strictly sort the list in Telescope?

@weilbith What you mean by that?

> Start Telescope with the prompt in normal mode

Yah this is possible by setting `opts.on_compete` to a list with a function that execute `vim.cmd"stopinsert"`, btw opts is what get passed as first argument to pickers.new

Users can do this is well
```lua
local fd_in_normal_mode = function()
  return require'telescope.builtin'.find_files{ 
    on_complete = { 
      function() 
         vim.cmd"stopinsert" 
      end 
    } 
  }
end
```

This might be better be default for most octo pickers.

> And it would be also great if you could somehow see at which commit you currently are (maybe preselect it?) 

pre-select sounds tricky not sure how something like can be accomplished, I'll see how this can be possible, but for now, maybe conditional highlighting or extra text like [current] 

> Telescope preview window would show me the commit message?

Oh @pwntester this sound like a use case for https://github.com/nvim-telescope/telescope.nvim/pull/528, @Conni2461 idea is crazy good, we can steal it here :laughing: and cycle between say comments, commit diff, commit messages, metadata .... etc

**Comment by Conni2461** [comment] 2021-02-24 18:14
Okay guys i am reading up on this. What tami says with normal mode is no longer correct. Give me like 10 minutes

**Comment by weilbith** [comment] 2021-02-24 18:18
> @weilbith What you mean by that?

@tami5 just that commits are strictly ordered (as long as they are no merge commits). If we populate the list of commits with Telescope the picker list should be sorted always as the commit order in git.

> Oh @pwntester this sound like a use case for nvim-telescope/telescope.nvim#528, @Conni2461 idea is crazy good, we can steal it here 😆 and cycle between say comments, commit diff, commit messages, metadata .... etc

I know this is a bad trait to say this, but the origin idea was by me. 😜 Just that I was so busy/lazy to implement it that @Conni2461 was so kind to finally implement it. Props to him. Love his work on Telescope. 🚀

**Comment by weilbith** [comment] 2021-02-24 18:20
Regarding the normal mode dicussion: what about the other question of @pwntester to just remove the prompt window at all for this case? So it is just about selecting an entry from the picker window directly?

**Comment by tami5** [comment] 2021-02-24 18:20
> I know this is a bad trait to say this, but the origin idea was by me.  Just that I was so busy/lazy to implement it that @Conni2461 was so kind to finally implement it. Props to him. Love his work on Telescope.

hhhhh ohh yah I remember, sorry about that, this is just how open source works :laughing: :laughing:

**Comment by weilbith** [comment] 2021-02-24 18:22
> In the other hand, I dont think you can scroll the result buffer, so if you get more commits than the height of the results windows you would lose some results.

True. That is a serious issue. It depends on the screen size and the used layout of Telescope. Hopefully this is not an issue for many scenarios and PR-branches. But we need to think about it.
What do our in-house Telescope guys say about this?

**Comment by tami5** [comment] 2021-02-24 18:24
> Regarding the normal mode dicussion: what about the other question by @pwntester to just remove the prompt window at all for this case? So it is just about selecting an entry from the picker window directly? Is that possible? I though to remember it was possible to disable the preview window. So maybe that's the same concept?

remove prompt window? what you mean different layout?

**Comment by Conni2461** [comment] 2021-02-24 18:27
> Is it possible to strictly sort the list in Telescope

You can sort the list upfront. That means if `finder.new_table` is used the sorting initial will be like the sorting in the [1, n] indexed table. For `finders.new_oneshot_job` it would be more difficult because it handles results on stdout. Which means we need to do some other sorting. After the job is done. (I have no idea what octo is using)

 > prompt in normal mode
 
 That possible on a telescope level and should work with all pickers: `lua require'telescope.builtin'.fd{ initial_mode='normal' }`
 
 > preselect
 
 For preselecting there is `default_selection_index` which can be set when doing `pickers.new`. It should just not exceed the maximal displayed results. Because there is currently no paging. So i have no idea what happens if that is >. Probably nothing bad.
 
> Not sure if you can even hide the prompt buffer window

Not sure about this one but we can maybe add something. Need to check :)

> cycle

Is super cool. Thanks for suggesting @weilbith. I wanna merge that this week. Need to talk with tj about interfaces tho. 

> scroll the result buffer

Thats a really tricky issue because how we store the results. Only like the displayed results are correctly sorted. Buts its on our list for a Post 1.0 release.

**Comment by Conni2461** [comment] 2021-02-24 18:28
> pre-select sounds tricky not sure how something like can be accomplished

@tami5 talking about things that are already possible :| The typical project manager

**Comment by weilbith** [comment] 2021-02-24 18:33
@tami5 why did you actually brought up the preview cycle topic? What would you use it here for? :thinking:

**Comment by weilbith** [comment] 2021-02-24 18:37
Btw: there is no commit message previewer yet, isn't there?

**Comment by Conni2461** [comment] 2021-02-24 18:40
> Btw: there is no commit message previewer yet, isn't there?

You mean in core. We can add the commit message at the top of the previewer. Sounds like a good idea and its not hard to do. Otherwise the message is only shown in results list. Which isn't helpful for multi line messages / commit messages with description.

**Comment by tami5** [comment] 2021-02-24 18:41
> @tami5 why did you actually brought up the preview cycle topic? What would you use it for here? 
> Just the different git diff previewers?


cycle between pr comments, commit diff, commit messages, metadata .... etc. I think it might best for pr  picker

**Comment by weilbith** [comment] 2021-03-19 09:29
@pwntester if you might search for the next feature to work on: this is atm the major issue for me to use Octo in daily professional work. I tried it over and over again, but so often I look at changes and wonder what the authors intention was and which of all theses changes in the quickfix window actually belong together. So I stop my review and switch to the browser again.

**Comment by pwntester** [comment] 2021-03-20 22:15
Things to consider:
- Should be very easy to extend current logic to support reviews at the commit level
- [GraphQL API](https://docs.github.com/en/graphql/reference/input-objects#addpullrequestreviewthreadinput) does not support adding comments at a given commit. [REST API does](https://docs.github.com/en/rest/reference/pulls#create-a-review-comment-for-a-pull-request) 
- Commit review comments cannot be added to an on-going (pending) review. We need to buffer all comments offline and submit them as part of `Octo review submit`, or submit them as they are added (each comment will be considered as a single review itself). The WebUI seems to do the later
- We need to duplicate a lot of logic. eg: when adding a comment, we need to check if we are reviewing the whole PR or a single commit and then call the REST or GraphQL APIs ...

@weilbith how does the following sound to you:
- `Octo review commit`: Show menu showing an ordered list of commits. On selection, show changed files in the commit (similarly to `Octo review start`)
- When adding a new comment, submit it to GH straight away which will result in a "single comment" review.
- No need to do `Octo review start`/`Octo review submit` which will make it no consistent with existing approach
- `Octo review comments` should show all comments for the selected commit and allow modify and delete them

**Comment by weilbith** [comment] 2021-03-20 22:24
I'm a little confused. Why - from the API usage - does this differ from a normal review. Shouldn't it be just a matter of how the diffs get presented to the user? Instead of packing all changes into one view, we take only parts of them based on their commit and only show those in the UI as before for all changes. The user is free to switch the current selection by a menu (as you suggested). But this only affects the UI, or more exact just the quickfix list. Everything else should remain 100% the same. From my perspective.

**Comment by weilbith** [comment] 2021-03-20 22:29
So here is how I imagine it: 
- start review as usual with `Octo review start`
- for the moment the "quickfix" list gets populated as always (could be tweaked later to let the user configure a preferred way, but this way it is like the WebUI where you first see all commit changes)
- there is a command like `Octo review commits` which brings a (Telescope?!) popup with a sorted list of commits, the currently selected one is highlighted (none initially) and the preview shows the message (could be reused to just read the message of the current commit again)
- when a commit of the list gets selected, the quickfix list gets adopted to only includes the changes in this PR for this commit
- the user can do his stuff as usual and adds comments, which get added immediately to the API for the pending review
- user can call commit pop-up again and select the next (or maybe an already visited one again) commit, the quickfix list adopts and so on

**Comment by weilbith** [comment] 2021-03-20 22:30
l know there is this feature in GitHub to also comment on single commits. But as I know this is totally unrelated to PRs. Honestly I have no clue what to use it for.

**Comment by weilbith** [comment] 2021-03-20 22:32
Having single review comments one after each other is super annoying. First the PR author gets ton of notifications again and again. Second, sometimes you comment on things and at a later commit you understand the intention of the author and can delete the comment or adopt it. The author should not have seen this comment already. Also does clutter the PR history and everything. When do you do the final review statement with the (eventual) confirmation etc...

**Comment by weilbith** [comment] 2021-03-20 22:36
Ah and quickfix lists can have names which usually get displayed in the status line. There I would put the info if the user is viewing all changes or a single commit. Best shown with commit hash and commit message header (author? date?)

**Comment by pwntester** [comment] 2021-03-20 22:45
Unfortunately, the GH API does not support this.

For reviews at the PR level, you can create a Review with no comments that will remain in Pending state, then you can add comments (also as Pending), and when ready submit the review with a review status and top-level comment. This is supported by v4 API (GraphQL)

For reviews at the Commit level, we need to use the v3 API (REST) which does not support Pending reviews. So we need to A) submit the comments as soon as they are saved which will create single-comment reviews (I think this is the way the webUI works too) or B) write comments locally and when ready create a new review with all comments (but you still need to submit a new review for each commit). You cannot add comments to a Pending review and when done submit the review and a top-level comment.

A) [Create a commit comment](https://docs.github.com/en/rest/reference/pulls#create-a-review-comment-for-a-pull-request). This API allows us to create single-review comments for a specific `commit_id`

B) [Create a review for a pull request](https://docs.github.com/en/rest/reference/pulls#create-a-review-for-a-pull-request). This API allows us to create a review with a set of comments for a specific `commit_id`

[GraphQL API AddPullRequestReviewThreadInput](https://docs.github.com/en/graphql/reference/input-objects#addpullrequestreviewthreadinput) does not take any `commit_id` :(

**Comment by pwntester** [comment] 2021-03-20 22:58
To be more exact, with v3 API you can:
- [Create a PENDING review](https://docs.github.com/en/rest/reference/pulls#create-a-review-for-a-pull-request)
- [Update a PENDING review](https://docs.github.com/en/rest/reference/pulls#update-a-review-for-a-pull-request). **But you cannot add new comments as part of the update** 🤷🏼‍♂️ 
- [Submit PENDING review](https://docs.github.com/en/rest/reference/pulls#submit-a-review-for-a-pull-request)

**Comment by pwntester** [comment] 2021-03-20 23:12
> GraphQL API AddPullRequestReviewThreadInput does not take any commit_id :(

Scratch that, I just found this [other mutation](https://docs.github.com/en/graphql/reference/input-objects#addpullrequestreviewcommentinput) with takes a commit OID. So in theory we can keep the original approach:
- create a review
- add PENDING comments for a specific commit
- add PENDING comments for the whole PR
- submit PENDING review

🎉 🎉

**Comment by weilbith** [comment] 2021-03-20 23:13
l'll look into your resources, but here some quick input:

> (I think this is the way the webUI works too)

The WebUI explicitly asks you which of both versions you want to do: make it a single comment or start a review, also when I select a single commit. And I can come back to my review later and all the comments are still there and in pending mode. I think if I go to the PR main thread I can even see my pending comments. And as I do reviews commit by commit in 98% of all cases I assume this was here true as well.

> You cannot add comments to a Pending review and when done submit the review and a top-level comment.

Well, I thought this is exactly how it works atm.

---

I think there is one important part: I don't want to add a comment to a commit nor do I want to review a single commit. That this does not work the way I have described seems obvious. What I want, and what I think is exactly how the WebUI is doing as I'm using this feature like forever when this was added, is that you still do a normal PR review but it is only about the representation of the data. In fact you should not be in need to adopt a single API query in Octo. Everything is already there.

**Comment by weilbith** [comment] 2021-03-20 23:14
Ah, sorry I haven't seen that you posted a comment while I was writing. 🙈 
This read like amazing news. 👍🏾 🥳

**Comment by pwntester** [comment] 2021-03-20 23:26
Unfortunately, [addpullrequestreviewcomment](https://docs.github.com/en/graphql/reference/input-objects#addpullrequestreviewcommentinput) does NOT seem to support multi-line comments as [addpullrequestreviewthread](https://docs.github.com/en/graphql/reference/mutations#addpullrequestreviewthread) does :(

**Comment by pwntester** [comment] 2021-03-20 23:29
The problem is that [addpullrequestreviewthread](https://docs.github.com/en/graphql/reference/mutations#addpullrequestreviewthread) does NOT allow us to select a commit OID so if you comment on a line that is later deleted on a later commit, the comment will be marked as outdated and not shown, for example.

**Comment by weilbith** [comment] 2021-03-20 23:46
> The problem is that [addpullrequestreviewthread](https://docs.github.com/en/graphql/reference/mutations#addpullrequestreviewthread) does NOT allow us to select a commit OID so if you comment on a line that is later deleted on a later commit, the comment will be marked as outdated and not shown, for example.

I think this is normal behavior in the WebUI as well. So I would not mind it.

---

It is late here. I'll try to read up the API for reviews tomorrow. I still think this should be a UI only feature/issue. If there are special and useful endpoints we could use, fine. But I actually think we could do it completely without. Also it might be a little tweaky. We will see.
I hope so much that this becomes possible. Combined with what got added recently and eventually some notification system (when it becomes possible) to close the gap, I'll use this plugin always and each day to do my issue/PR work.

**Comment by pwntester** [comment] 2021-03-21 15:08
> I think this is normal behavior in the WebUI as well. So I would not mind it.

Using [addpullrequestreviewcomment](https://docs.github.com/en/graphql/reference/input-objects#addpullrequestreviewcommentinput) (specifying commitOID) I added a comment to line 734 of commands.lua [here](https://github.com/pwntester/octo.nvim/pull/94/commits/31c50f841152691ecb36f0e89cd5f6438325527c#diff-e06ff74eef80b0a11e2237110975e116f69d392a77ffc752f79a4e9524eb000eR734) and it correctly appears in line 725 [here](https://github.com/pwntester/octo.nvim/pull/94/files?file-filters%5B%5D=.lua&file-filters%5B%5D=.vim#diff-e06ff74eef80b0a11e2237110975e116f69d392a77ffc752f79a4e9524eb000eR725)

However, if I use [addpullrequestreviewthread](https://docs.github.com/en/graphql/reference/mutations#addpullrequestreviewthread) to comment on line 734 of commands.lua, it will apply the comment at line 734 of the latest commit which is not even a valid line to comment on (outside diff hunk). 

Therefore, to comment at the commit level, we MUST use `addpullrequestreviewcomment` which does not support multi-line comments (at least using the API)

**Comment by weilbith** [comment] 2021-03-21 19:03
Hmm. So I gave it an experiment and this is the network devtools dump of adding to comments to a PR in pending mode. Unfortunately I forgot to include the finalizing POST of the review which was send to `https://github.com/pwntester/octo.nvim/pull/132/reviews`. I hope this leaks no secrets.

**Comment by weilbith** [comment] 2021-03-21 19:05
Ah sorry, I realized the dump contains secret data. So creating pending comments to a single commit of the PR goes to POST `https://github.com/pwntester/octo.nvim/pull/132/review_comment/create`

**Comment by pwntester** [comment] 2021-03-21 22:08
> So creating pending comments to a single commit of the PR goes to POST https://github.com/pwntester/octo.nvim/pull/132/review_comment/create

I checked that out but I don't see how these comments are bound to an existing review id. This endpoint is similar to https://docs.github.com/en/rest/reference/pulls?query=is%3Apr+is%3Aopen+sort%3Aupdated-desc#create-a-review-comment-for-a-pull-request but as mentioned above, this endpoint does not allow to assign comments to an existing review id

**Comment by younger-1** [comment] 2021-10-13 16:56
Sounds good!

**Comment by ldelossa** [comment] 2022-04-02 04:17
@pwntester any chance this gets finished off? Im kinda stuck with Octo right now for the same reason. Its difficult to perform reviews if we cannot filter the file panel in a per-commit fashion, viewing the commit message and file changes in said commit.

**Comment by pwntester** [comment] 2022-05-18 12:35
I have started working on this on #294 Feel free to help test/review

**Comment by pwntester** [comment] 2022-05-23 13:00
#294 has been merged, please test it and let me know if you find any issues

**Closed by pwntester** 2022-05-23 13:00 UTC
Labels: enhancement
