### ISSUE TITLE
[Feature Request] Add support for mason's gh.cmd.

### ISSUE THREAD

**Issue by mao-yining** [pwntester/octo.nvim#583] opened 2024-08-25 10:51 UTC
## Issue Description

Type: _feature request_

### Describe what happened (or what feature you want)

If I install gh from mason, it will has a gh.cmd in its bin.

Now octo only work when gh.exe was in the env, if I only add gh.cmd in my env , it won't work.

So, I have to add a special env for the gh.exe, it's not pretty.

### Describe what you expected to happen

Add support for mason's gh.cmd.

### How to reproduce it (as minimally and precisely as possible)

1. use mason.nvim install gh
2. keep only a gh.cmd in the env (add /nvim-data/mason/bin in the env
3. start octo

### Tell us your environment

windows 11 neovim v0.10.1

**Comment by wd60622** [comment] 2024-10-02 16:15
Closing because duplicate of  #582

**Closed by wd60622** 2024-10-02 16:15 UTC
