### ISSUE TITLE
Octo review submit box has strange behavior

### ISSUE THREAD

**Issue by aareman** [pwntester/octo.nvim#180] opened 2021-07-20 14:47 UTC
## Issue Description

Type: *bug report*

### Describe what happened

The `Octo review submit` dialog is very buggy for me. When writing the top level review comment if I press escape I get
![image](https://user-images.githubusercontent.com/10500823/126344055-2ff913e1-b27a-4ce8-868d-64c05970a85b.png)
Which is distracting. Also if I leave that buffer by accident I lose my comments.

### Describe what you expected to happen
Could it be a normal buffer that allows me to use regular vim motions to edit. (filetype could be set to markdown too).

Would make the editing more intuitive, and not lose work. Similar to how github handles that box. Where you can add a comment, go back to the review, and then edit it until you do the final submission.

### How to reproduce it (as minimally and precisely as possible)

1. Octo review start
2. Octo review submit
3. press `<esc>` or leave submit buffer

### Tell us your environment
ubuntu 20
![image](https://user-images.githubusercontent.com/10500823/126344504-76042d88-74b9-4a96-ac51-0fb9177ccaef.png)

### Anything else we need to know?

Great plugin, thank you very much

**Comment by pwntester** [comment] 2021-07-21 20:55
Thanks for the report. I cant reproduce the issue though. What is the output of `:map <esc>` when you are in the submit float? 

> Could it be a normal buffer that allows me to use regular vim motions to edit. (filetype could be set to markdown too).

It is actually a regular buffer and the syntax applied is markdown. It should allow all regular vim motions. 

> Would make the editing more intuitive, and not lose work. Similar to how github handles that box. Where you can add a comment, go back to the review, and then edit it until you do the final submission.

Interesting, Ive never used it that way. I will take a look into it, thanks for the suggestion

**Comment by pwntester** [comment] 2022-04-26 17:07
@mmirus Thanks for the hint, I dont use which-key but it may be incompatibilities.

I will make the comment buffer a regular one (rather than a scratch one) so that the float can be closed and `Octo review submit` will bring it again if called multiple times. Would that work for you @aareman ?

**Comment by aareman** [comment] 2022-06-29 15:14
@pwntester I think that would work. Thank you.

**Comment by pwntester** [comment] 2022-06-29 15:52
Nice, closing for now, let me know if you get into any problems

**Closed** 2022-06-29 15:52 UTC
Labels: enhancement

**Comment by aareman** [comment] 2022-10-11 07:31
I think that sounds good. How would one close a floating window without losing the buffer?


________________________________
